services:
  - type: web
    name: vikas-caterings
    env: node
    buildCommand: rm -rf dist && npm install && npm run build && npm install --prefix server
    startCommand: node server/index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: "*"
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
